// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction/index.svelte';
import Hero from './Hero/index.svelte';
import ImageGallery from './ImageGallery/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	call_to_action: CallToAction,
	hero_section: Hero,
	image_gallery: ImageGallery,
	rich_text: RichText
};
